# Generated by Django 6.0.4 on 2026-05-24 10:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=255)),
                ('model_name', models.CharField(max_length=255)),
                ('focal_length_min', models.IntegerField(blank=True, null=True)),
                ('focal_length_max', models.IntegerField(blank=True, null=True)),
                ('lens_type', models.CharField(choices=[('anamorphic', 'Anamorphic'), ('spherical', 'Spherical'), ('other', 'Other')], default='spherical', max_length=255)),
                ('notable_films', models.ManyToManyField(blank=True, related_name='lenses', to='films.film')),
            ],
        ),
        migrations.CreateModel(
            name='Shot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('lighting_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shots', to=settings.AUTH_USER_MODEL)),
                ('films', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shots', to='films.film')),
                ('lens_used', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shots', to='films.lens')),
            ],
        ),
    ]
