# Generated by Django 6.0.4 on 2026-05-24 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_lens_shot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='film',
            old_name='Cinematographer',
            new_name='cinematographer',
        ),
        migrations.RenameField(
            model_name='shot',
            old_name='films',
            new_name='film',
        ),
    ]
