# Generated by Django 6.0.4 on 2026-05-25 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0003_rename_cinematographer_film_cinematographer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LightingSetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setup_type', models.CharField(choices=[('three_point', 'Three Point'), ('motivated', 'Motivated'), ('natural', 'Natural'), ('high_key', 'High Key'), ('low_key', 'Low Key'), ('other', 'Other')], default='other', max_length=50)),
                ('key_light_notes', models.TextField(blank=True, null=True)),
                ('fill_notes', models.TextField(blank=True, null=True)),
                ('equipment_list', models.JSONField(blank=True, default=list)),
                ('shot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lighting_setups', to='films.shot')),
            ],
        ),
    ]
