# Generated by Django 6.0.4 on 2026-05-25 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0004_lightingsetup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='film',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='lightingsetup',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='shot',
            options={'ordering': ['-created_at']},
        ),
    ]
