# Generated by Django 6.0.4 on 2026-05-25 19:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0005_alter_film_options_alter_lightingsetup_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('inspiration', 'Inspiration'), ('technique', 'Technique'), ('director_study', 'Director Study')], default='inspiration', max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='references', to=settings.AUTH_USER_MODEL)),
                ('linked_film', models.ManyToManyField(blank=True, related_name='references', to='films.film')),
                ('linked_shot', models.ManyToManyField(blank=True, related_name='references', to='films.shot')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
